context:
  version: 3.0.5

package:
  name: xeus
  version: '{{ version }}'

source:
  url: https://github.com/jupyter-xeus/xeus/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4e02ab1603e81f0f76a9a4469af05c2af7e1551b0e0a5718c4b4f6ea125ed76f

build:
  number: 0

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja
  host:
    - nlohmann_json
    - xtl


about:
  home: https://github.com/jupyter-xeus/xeus
  license: BSD-3
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus
  doc_url: https://github.com/jupyter-xeus/xeus
  dev_url: https://github.com/jupyter-xeus/xeus

extra:
  recipe-maintainers:
    - DerThorsten
    - JohanMabille

