context:
  name: numcodecs
  version: 0.14.1

package:
  name: numcodecs
  version: ${{ version }}

source:
- url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{
    version }}.tar.gz
  sha256: 00a364924fd2d600bcce6e2ced96b47c40eb5f9d84bf4b0207aa208d9ce6cd1c
  # patches:
  # - patches/fixblosc.patch
  # - patches/fixsetup.patch
  # - patches/fixzlib.patch
- path: setup.py

build:
  number: 0

requirements:
  build:
  - ${{ compiler("c") }}
  - cross-python_emscripten-wasm32
  - cython
  - python
  - pip
  - setuptools_scm
  - numpy
  host:
  - numpy
  - python
  run:
  - numpy
  - msgpack

tests:
- script: pytester
  files:
    recipe:
    - test_import_numcodecs.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run
