context:
  version: 9.2.6

package:
  name: VTK
  version: '{{ version }}'

source:
  url: https://github.com/Kitware/VTK/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5df02a12ab7d53e2262cf254e5430ef50a185366d1cec971fd10089e775b00e6

build:
  number: 0

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja
  host:
    - bzip2
    - zlib
    - rapidjson
    - boost-cpp


about:
  home: https://github.com/Kitware/VTK
  license: BSD-3-Clause
  license_family: BSD-3-Clause
  license_file: Copyright.txt
  summary: VTK is The Visualization Toolkit (VTK) 
  doc_url: https://github.com/Kitware/VTK
  dev_url: https://github.com/Kitware/VTK

extra:
  recipe-maintainers:
    - DerThorsten

