context:
  version: 0.27.3

package:
  name: xwidgets
  version: '{{ version }}'

source:
  url: https://github.com/jupyter-xeus/xwidgets/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5c5d000582efcf0c782c09663936ba6a2bebca94a5a6e42da187f7b00d649c8f

build:
  number: 0

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja
  host:
    - xtl >=0.7,<0.8
    - nlohmann_json
    - xeus >=3.0,<4.0
    - xproperty >=0.11.0,<0.12
  run:
    - xtl >=0.7,<0.8
    - nlohmann_json
    - xeus >=3.0,<4.0
    - xproperty >=0.11.0,<0.12

about:
  home: https://github.com/jupyter-xeus/xwidgets
  license: BSD-3
  license_family: BSD-3
  license_file: LICENSE
  summary: xtl
  doc_url: https://github.com/jupyter-xeus/xwidgets
  dev_url: https://github.com/jupyter-xeus/xwidgets

extra:
  recipe-maintainers:
    - DerThorsten
    - JohanMabille

