context:
  version: 5.2.2
  name: liblzma

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/xz-mirror/xz/releases/download/v${{version}}/xz-${{version}}.tar.gz
  sha256: 73df4d5d34f0468bd57d09f2d8af363e95ed6cc3a4a86129d2f2c366259902a2
  # url: http://zlib.net/zlib-{{ version }}.tar.gz

build:
  number: 0


requirements:
  build:
  - ${{ compiler("c") }}
  - cmake
  - ninja

about:
  summary: Massively spiffy yet delicately unobtrusive compression library
  license_family: Other

  description: |
    zlib is designed to be a free, general-purpose, lossless data-compression
    library for use on virtually any computer hardware and operating system.

  homepage: http://zlib.net/
extra:
  recipe-maintainers:
  - DerThorsten
