context:
  version: "2.8.0"

package:
  name: libutf8proc
  version: '{{ version }}'

source:
  - url: https://github.com/JuliaStrings/utf8proc/archive/v{{ version }}.tar.gz
    sha256: a0a60a79fe6f6d54e7d411facbfcc867a6e198608f2cd992490e46f04b1bcecc

build:
  number: 0

requirements:
  build:
    - '{{ compiler("c") }}'
    - cmake
    - make
    - ninja

about:
  home: https://juliastrings.github.io/utf8proc/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: a clean C library for processing UTF-8 Unicode data
  description: |
    utf8proc is a small, clean C library that provides Unicode normalization,
    case-folding, and other operations for data in the UTF-8 encoding
  doc_url: https://juliastrings.github.io/utf8proc/doc/
  dev_url: https://github.com/JuliaStrings/utf8proc

extra:
  recipe-maintainers:
    - martinRenou
