context:
  name: only_py_tests_simple
  version: "1.0.0"

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'


build:
  number: 2

requirements:
  run:
    - numpy
    - scipy
    - pyarrow
    
about:
  home: only_py_tests

extra:
  recipe-maintainers:
    - DerThorsten
