context:
  version: 0.6.1

package:
  name: xeus-sqlite
  version: '{{ version }}' 

source:
  url: https://github.com/jupyter-xeus/xeus-sqlite/archive/refs/tags/{{ version }}.tar.gz
  sha256: 644c1262bc4075d48533134cf7b6cd0ce4cd597b6914966526b17621ae60dffc

build:
  number: 0

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja
  host:
    - nlohmann_json
    - tabulate
    - xvega
    - xvega-bindings
    - SQLiteCpp
    - xeus-lite
    - xeus >=3.0.5,<4.0
    - xtl >=0.7,<0.8



about:
  home: https://github.com/jupyter-xeus/xeus-sqlite
  license: BSD-3
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus-sqlite
  doc_url: https://github.com/jupyter-xeus/xeus-sqlite
  dev_url: https://github.com/jupyter-xeus/xeus-sqlite

extra:
  recipe-maintainers:
    - DerThorsten