context:
  version: 2.2.0
  cross_target_plattform: emscripten-wasm32
  target_plattform: emscripten-wasm32
  default_abi_level: 2.2

package:
  name: numpy
  version: ${{ version }}
source:
  url: https://github.com/numpy/numpy/releases/download/v${{ version }}/numpy-${{
    version }}.tar.gz
  sha256: 140dd80ff8981a583a60980be1a655068f8adebf7a45a06a6858c873fcdcd4a0
build:
  number: 0

requirements:
  build:
  - ${{ compiler("c") }}
  - cross-python_${{target_platform}}
  - cython
  - meson-python
  - ninja >=1.8.2
  - pip >=24.0
  - pkg-config
  - python
  host:
  - python
  run_exports:
    - numpy >=${{ default_abi_level }},<3
tests:
- script: pytester
  requirements:
    build:
    - pytester
    run:
    - pytester-run
  files:
    recipe:
    - test_numpy.py

about:
  homepage: http://numpy.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: The fundamental package for scientific computing with Python.

extra:
  recipe-maintainers:
  - DerThorsten
