context:
  version: 2.1.0
  cross_target_plattform: emscripten-wasm32
  target_plattform: emscripten-wasm32

package:
  name: numpy
  version: ${{ version }}
source:
  url: https://github.com/numpy/numpy/releases/download/v${{ version }}/numpy-${{
    version }}.tar.gz
  sha256: 7dc90da0081f7e1da49ec4e398ede6a8e9cc4f5ebe5f9e06b443ed889ee9aaa2
build:
  number: 0

requirements:
  build:
  - ${{ compiler("c") }}
  - cross-python_${{target_platform}}
  - cython
  - meson-python
  - ninja >=1.8.2
  - pip >=24.0
  host:
  - python
  run:
  - python

tests:
- script: pytester
  requirements:
    build:
    - pytester >= 0.9.0
    run:
    - pytester-run >= 0.9.0
  files:
    recipe:
    - test_numpy.py

about:
  homepage: http://numpy.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: The fundamental package for scientific computing with Python.

extra:
  recipe-maintainers:
  - DerThorsten
