context:
  name: cross-python_emscripten-wasm32
  version: "3.13.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

build:
  number: 1

requirements:

  run:
    - coreutils
    - crossenv >=1.2
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - rsync
    - sed
    - python
    - setuptools
    - pip
    
about:
  summary: cross-python

extra:
  recipe-maintainers:
    - DerThorsten
