context:
  version: '9.8.0.2'

package:
  name: smesh
  version: '{{ version }}'

source:
# - url: https://github.com/trelau/SMESH/archive/refs/tags/v{{ version }}.tar.gz
#   sha256: a106ecb7d8c9e39f0485da0eba50e9010548c14a5d35794181e680423940e54b
    git:

build:
  number: 0

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'
    - ninja
    - cmake
    - python-patch
