context:
  version: "11.0.0"

package:
  name: arrow-python
  version: '{{ version }}'

source:  
  - url: https://github.com/apache/arrow/archive/refs/tags/apache-arrow-{{version}}.dev.tar.gz
    patches:
      - patches/wasm.patch

build:
  number: 0

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cross-python_emscripten-32
    - python
    - cython
    - setuptools
    - setuptools_scm
    - numpy
  host:
    - python
    - pip
    - cffi
    - arrow
    - re2
    - libutf8proc
  run:
    - numpy
    - python
    - libffi
    - pycparser
    - cloudpickle
    - hypothesis
    - fsspec


about:
  home: https://arrow.apache.org/
  license: Apache
  license_family: Apache
  license_file: LICENSE.rst
  summary: 'Arrow: A cross-language development platform for in-memory analytics'
  description: |
    Arrow: A cross-language development platform for in-memory analytics
  doc_url: https://arrow.apache.org/
  dev_url: https://github.com/apache/arrow.git

extra:
  recipe-maintainers:
    - Klaim


