context:
  version: 0.7.3

package:
  name: xeus-lua
  version: '{{ version }}'

source:
  url: https://github.com/jupyter-xeus/xeus-lua/archive/refs/tags/{{ version }}.tar.gz
  sha256: f0f8e465daacb5ae13572999374a8a785486ea7bcc83fe10c11254099eb31d37

build:
  number: 0

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja
  host:
    - lua
    - nlohmann_json
    - xeus-lite
    - xeus >=3.0.5,<4.0
    - xtl >=0.7,<0.8
    - xcanvas >=0.4,<5.0
    - xwidgets >=0.27.3,<0.28

test:
  commands:
    - sel(emscripten): test -f $PREFIX/bin/xlua_wasm.wasm
    - sel(emscripten): test -f $PREFIX/bin/xlua_wasm.js

about:
  home: https://github.com/jupyter-xeus/xeus-lua
  license: BSD-3
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus-lua
  doc_url: https://github.com/jupyter-xeus/xeus-lua
  dev_url: https://github.com/jupyter-xeus/xeus-lua

extra:
  recipe-maintainers:
    - DerThorsten
    - martinRenou
    - JohanMabille
