context:
  name: cross-r-base_emscripten-wasm32
  version: 4.5.2
<<<<<<< Updated upstream

package:
  name: ${{ name }}
  version: ${{ version }}
=======
>>>>>>> Stashed changes

build:
  number: 2

<<<<<<< Updated upstream
requirements:
  run:
  - r-base ==${{ version }} h15dba0b_1
  - emscripten_emscripten-wasm32
=======
outputs:
- package:
    name: ${{ name }}
    version: ${{ version }}
  requirements:
    run:
      - r-base-abi ==${{ version }}
      - emscripten_emscripten-wasm32
    run_exports:
      strong:
      - r-base-abi ==${{ version }}
  # tests:
  # - package_contents:
  #     files:
  #     - etc/conda/activate.d/activate_z-${{ name }}.sh
  #     - etc/conda/deactivate.d/deactivate_z-${{ name }}.sh
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes

tests:
- package_contents:
    files:
    - etc/conda/activate.d/activate_z-${{ name }}.sh
    - etc/conda/deactivate.d/deactivate_z-${{ name }}.sh

about:
  summary: Package to cross-compile R packages to WebAssembly using Emscripten.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
  - IsabelParedes
