context:
  version: 0.2.0

package:
  name: xeus-nelson
  version: '{{ version }}'

source:
  url: https://github.com/jupyter-xeus/xeus-nelson/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6569fc17803a0bead1cd8638bc3462cb664f486bd3d40b9706a9b6f74aeb94c9 

build:
  number: 2

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja
  host:
    - nelson
    - nlohmann_json
    - xeus-lite
    - xeus >=3.0.5,<4.0
    - xtl >=0.7,<0.8

test:
  commands:
    - sel(emscripten): test -f $PREFIX/bin/xnelson_wasm.wasm
    - sel(emscripten): test -f $PREFIX/bin/xnelson_wasm.js

about:
  home: https://github.com/jupyter-xeus/xeus-nelson
  license: BSD-3
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus-nelson
  doc_url: https://github.com/jupyter-xeus/xeus-nelson
  dev_url: https://github.com/jupyter-xeus/xeus-nelson

extra:
  recipe-maintainers:
    - DerThorsten
    - martinRenou
    - JohanMabille
