context:
  version: '1.11'

package:
  name: sympy
  version: '{{ version }}'

source:
  - url: https://pypi.io/packages/source/s/sympy/sympy-{{ version }}.tar.gz
    sha256: 1fe96b4c56bb7a7630cdf150a6cd98bc97a79e6be233e30502aba1cf54dee33d

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - mpmath
    - pip
    - python
  run:
    - mpmath
    - python

extra:
  emscripten_tests:
    python:
      pytest_files:
        - test_import_sympy.py
