context:
  version: 3.4.2
  am_version: 1.15
  name: libffi
package:
  name: '{{name}}'
  version: '{{ version }}'

source:
  #- url: https://github.com/emscripten-forge/{{name}}/archive/refs/tags/{{version}}.tar.gz
  #  sha256: 21211596df09778de7ebfc34267b6759da5ef5bfb0ce7c8436b098e9bc83b2f3
  - path: /Users/thorstenbeier/src/pyodide_clean
build:
  number: 3
  ignore_run_exports:
    - nodejs

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - '{{ compiler("c") }}'
    - python=3.11
    - nodejs
    - ccache
    - f2c
    - pkg-config
    - swig
    - make
    - cmake
    - pkg-config
    - texinfo
    - autoconf
    - automake
    - libtool
    - patch # only needed on MacOS
    - sed # only needed on MacOS
    - wget


about:
  home: https://sourceware.org/libffi/
  license: MIT
  license_file: LICENSE
  summary: A Portable Foreign Function Interface Library.

  description: |
    The libffi library provides a portable, high level programming interface
    to various calling conventions. This allows a programmer to call any
    function specified by a call interface description at run-time.
  doc_url: https://sourceware.org/libffi/
  dev_url: https://github.com/libffi/libffi

extra:
  recipe-maintainers:
    - DerThorsten

