context:
  name: only_py_tests
  version: "1.0.0"

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'


build:
  number: 2

requirements:
  run:
    - python
    - pandas
    - arrow-python
    - matplotlib
    - scipy
    - ipython
    
about:
  home: only_py_tests

extra:
  recipe-maintainers:
    - DerThorsten
