context:
  version: 3.11.3
  build_py_version: "{{ '.'.join(version.split('.')[:2]) }}"

package:
  name: python
  version: '{{ version }}'

source:
  - url: https://www.python.org/ftp/python/{{ version }}/Python-{{ version }}.tgz
    sha256: 1a79f3df32265d9e6625f1a0b31c28eb1594df911403d11f3320ee1da1b3e048
    patches:
      - sel(emscripten): patches/0001-Public-pymain_run_python.patch
      - sel(emscripten): patches/0002-Patch-importlib-to-allow-modifications-to-ModuleNotF.patch
      - sel(emscripten): patches/0003-Add-emscripten-platform-support-to-ctypes.util.find_.patch
      - sel(emscripten): patches/0004-Allow-multiprocessing.connection-top-level-import.patch
      - sel(emscripten): patches/0005-gh-93839-Move-Lib-ctypes-test-to-Lib-test-test_ctype.patch
      - sel(emscripten): patches/0006-gh-93839-Move-Lib-unttest-test-to-Lib-test-test_unit.patch
      - sel(emscripten): patches/0007-gh-93839-Use-load_package_tests-for-testmock-GH-9405.patch
      - sel(emscripten): patches/0008-Move-test-directories.patch

build:
  # ATTENTION need to change build number in build string as well!

  number: 0
  # check with https://github.com/mamba-org/boa/issues/278
  string: h_hash_0_cpython

  # run_exports:
  #   strong:
  #     - '{{ pin_subpackage("python", max_pin="x.x") }}'
  skip_compile_pyc:
    - "**/*.py"

requirements:
  build:
    - sel(unix):          make           
    - sel(unix):          python {{ build_py_version }}
    - sel(emscripten):    "{{ compiler('c') }}"
  host:
    - bzip2
    - zlib
    - libffi
    - sqlite
    
about:
  home: todo
  summary: todo
  license: todo
  license_file: todo

extra:
  recipe-maintainers:
    - DerThorsten