context:
  name: lfortan
  version: "0.35.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
# - url: https://github.com/lfortran/lfortran/archive/refs/tags/v${{ version }}.tar.gz
#   sha256: 2e54c5cfe9a94fc572bfc39c51496203636f78fb04e8bc0809577c4e1713a2ac
  - git: https://github.com/lfortran/lfortran.git
    rev: eff69eecb3834500d4e78f55de69ae550776077f

build:
  number: 1

requirements:
  build:
  - clang
  - python
  - re2c
  - bison ==3.4
  - python
  - cmake =3.21.1 
  - make 
  - toml
  - binutils
  host:
  - python     
  - xeus =3.0.5
  - xeus-zmq =1.0.2
  - llvmdev =15
  - xtl
  - nlohmann_json =3.11.2
  - cppzmq
  - zlib
  - zstd-static =1.5.5

    
about:
  summary: lfortan

extra:
  recipe-maintainers:
    - DerThorsten
