context:
  version: 0.1.0

package:
  name: cockle
  version: ${{ version }}


build:
  number: 0

requirements:
  build:
    - ${{ compiler("cxx") }}
    - cmake

tests:
  - script:
    - test -f $PREFIX/bin/fs.js

about:
  homepage: https://github.com/jupyterlite/cockle
  license: 	BSD-3-Clause
  license_file: LICENSE
  summary: fs for cockle
  documentation: https://github.com/jupyterlite/cockle

extra:
  recipe-maintainers:
    - DerThorsten
