context:
  version: "3.11.3" # lets use same as python 
  name: "ssl"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://www.python.org/ftp/python/${{version}}/Python-${{version}}.tgz
  sha256: 1a79f3df32265d9e6625f1a0b31c28eb1594df911403d11f3320ee1da1b3e048

build:
  number: 0

requirements:
  build:
    - ${{ compiler("c") }}
  host:
    - openssl
    - python
  run:
    - openssl
    - python

tests:
  - script: pytester
    requirements:
      build:
        - pytester
      run:
        - pytester-run
    files:
      recipe:
        - test_ssl.py


about:
  license: Python-2.0
  license_file: LICENSE
extra:
  recipe-maintainers:
    - DerThorsten



