context:
  version: 2.13.0

package:
  name: pybind11
  version: ${{ version }}

source:
  url: https://github.com/pybind/pybind11/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 8ac2bd138ea3c12683d3496361af6bee0f7754f86bf050e6c61e3966de688215
  patches:
  - patches/0001-no-bitsize-check.patch
build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja
  host:
  - python


about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Seamless operability between C++11 and Python
  homepage: https://github.com/pybind/pybind11

extra:
  recipe-maintainers:
  - DerThorsten
