context:
  version: '3.7.0'
  name: h5py

package:
  name: '{{name}}'
  version: '{{ version }}'

source:
  - url: https://files.pythonhosted.org/packages/c5/40/7cf58e6230f0e76699f011c6d293dd47755997709a303a4e644823f3a753/h5py-3.7.0.tar.gz
    sha256: 3fcf37884383c5da64846ab510190720027dca0768def34dd8dcb659dbe5cbf3
  - path: patches/setup_configure.py
  - path: patches/setup_build.py

build:
  number: 0

requirements:
  build:
    - cmake
    - ninja
    - '{{ compiler("c") }}'
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - python
    - cython
    - numpy
    - setuptools
    - pkgconfig

  host:
    - numpy
    - hdf5
    - python

extra:
  emscripten_tests:
    python:
      pytest_files:
        - test_h5py.py
