context:
  version: "6.6.2"
package:
  name: pyomo
  version: "{{ version }}"

source: # pypi md5
  fn: Pyomo-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/P/Pyomo/Pyomo-{{ version }}.tar.gz
  sha256: c8ad55213ff8b1a2c4e469110db8079722d5a6f364c6c46a42e2f750fc9e4d26

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --install-option=--with-distributable-extensions --no-deps -vv"
  # entry_points:
  #   - pyomo=pyomo.scripting.pyomo_main:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - cython
    - pip

  host:
    - python
    - pybind11

  run:
    - python
    - setuptools
    - ply


about:
  home: http://pyomo.org
  license: "BSD-3-Clause"
  license_file: '{{ environ["RECIPE_DIR"] }}/Pyomo-LICENSE.txt'
  summary: 'Pyomo: Python Optimization Modeling Objects'
  license_family: BSD

extra:
  emscripten_tests:
    python:
      pytest_files:
        - test_pyomo.py

  recipe-maintainers:
    - DerThorsten
