context:
  version: 0.18.0
  name: pyjs
package:
  name: '{{name}}'
  version: '{{ version }}'
  
source:
  - url: https://github.com/emscripten-forge/{{name}}/archive/refs/tags/{{version}}.tar.gz
    sha256: 9e9e15f03827f39b3232324f30fcaf4058f7a1005fdeac63f456754e96c649a2
build:
  number: 1

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja
    - python
  host:
    - python
    - sqlite
    - zlib
    - bzip2
    - libffi
    - pybind11

about:
  home: https://github.com/emscripten-forge/pyjs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pyjs


extra:
  recipe-maintainers:
    - DerThorsten

