context:
  version: 1.3.1
  name: pyjs
package:
  name: '{{name}}'
  version: '{{ version }}'

source:
  - url: https://github.com/emscripten-forge/{{name}}/archive/refs/tags/{{version}}.tar.gz
    sha256: ee1bd418ef227f3cf586cf8818a514b424663b8f5527cc897c5fd3f91ebcdf01

build:
  number: 3

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja
    - python
  host:
    - python
    - sqlite
    - zlib
    - bzip2
    - libffi
    - pybind11

about:
  home: https://github.com/emscripten-forge/pyjs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pyjs

extra:
  recipe-maintainers:
    - DerThorsten
