context:
  version: 0.10.0
  name: pyjs
package:
  name: '{{name}}'
  version: '{{ version }}'
  
source:
  url: https://github.com/emscripten-forge/{{name}}/archive/refs/tags/{{version}}.tar.gz
  sha256: 60a0b1b2c0897d8ce76d2613720c85b987d059f6a2c4652d037c8b8064af5f6f

build:
  number: 1

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja
  host:
    - python
    - sqlite
    - zlib
    - bzip2
    - libffi
    - pybind11

about:
  home: https://github.com/emscripten-forge/pyjs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pyjs


extra:
  recipe-maintainers:
    - DerThorsten

