context:
  version: 0.11.2
  name: pyjs
package:
  name: '{{name}}'
  version: '{{ version }}'
  
source:
  url: https://github.com/emscripten-forge/{{name}}/archive/refs/tags/{{version}}.tar.gz
  sha256: 0478da0469268f0abeca77545907f1a9bc68743225a2a862c1c7ed88db32525f

build:
  number: 1

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja
  host:
    - python
    - sqlite
    - zlib
    - bzip2
    - libffi
    - pybind11

about:
  home: https://github.com/emscripten-forge/pyjs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pyjs


extra:
  recipe-maintainers:
    - DerThorsten

